ignore:
  # glob-parent   3.1.0      5.1.2     npm   GHSA-ww39-953v-wcq6  High
  - vulnerability: GHSA-ww39-953v-wcq6
  # json5         0.5.1      1.0.2     npm   GHSA-9c47-m6qq-7p4h  High
  - vulnerability: GHSA-9c47-m6qq-7p4h
  # loader-utils  0.2.17     1.4.1     npm   GHSA-76p3-8jx3-jpfq  Critical
  - vulnerability: GHSA-76p3-8jx3-jpfq
  # node-forge    0.10.0     1.3.0     npm   GHSA-cfm4-qjh2-4765  High
  - vulnerability: GHSA-cfm4-qjh2-4765
  # node-forge    0.10.0     1.3.0     npm   GHSA-x4jg-mjrx-434g  High
  - vulnerability: GHSA-x4jg-mjrx-434g
  # nth-check     1.0.2      2.0.1     npm   GHSA-rp65-9cf3-cjxr  High
  - vulnerability: GHSA-rp65-9cf3-cjxr
