name: kube-linter

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - .github/workflows/kube-linter.yml
      - docs/part**
  push:
    branches:
      - main
    paths:
      - .github/workflows/kube-linter.yml
      - docs/part**

permissions: read-all

jobs:
  command-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Extract yamls from README files
        run: |
          for FILE in $(find docs/part* -name "*.md" | sort); do
            echo "*** ${FILE}"
            sed -n '/^kubectl apply -f - << EOF/,/^EOF/p' "${FILE}" | sed 's/^EOF/---/;s/^kubectl apply -f - << EOF.*/---/' >> "${FILE}.yml"
            ls -la "${FILE}.yml"
          done

      - name: kube-linter
        uses: stackrox/kube-linter-action@ca0d55b925470deb5b04b556e6c4276ea94d03c3 # v1.0.4
        with:
          directory: docs
